<?php
/**
 * @file
 * For all things custom with the stanford jumpstart academic product.
 */

/**
 * Implements hook_help().
 */
function soe_jsa_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';
     */
    case 'soe_jsa':
      return '<p>' . t('Needs Work %email', array('%email' => l('SWS','mailto:soeithelp@stanford.edu'))) . '</p>';
  }
}
